 name: unidata
 channels:
   - conda-forge
 dependencies:
   - python>=3.6,<3.8
   - numpy
   - matplotlib
   - cartopy
   - jupyter
   - metpy
   - siphon
   - pandas<1.1.0
   - pip
   - xarray
   - ipywidgets
   - ffmpeg
   - boto3
   - botocore
   - jupyterlab
   - python-awips
